### PR TITLE
Normal

### PR DESCRIPTION
**Pull request by jkrempus**
- Added comments
- Use `fastUniformFloat` in Box-Muller
- Avoided the enforcement in Normal.opCall
- Always use at least double precision to compute the table for Ziggurat  algorithm(`intervalMinMax` doesn't converge for single precision with 256 layers or more).
- Made the handling of head and tale in `zigguratAlgorithmImpl` a bit more elegant
- Added a small optimization to `zigguratAlgorithm`
- Renamed `NormalZigguratEngine64` to `NormalZigguratEngine` and got rid of the `NormalZigguratEngineImpl` wrapper template. Also changed the number of layers to 128.

### CODE REVIEW

**Comment by WebDrake** [comment]
LGTM.  We need to add in an enforcement on sigma in the Normal constructor, I'll do that myself.  Then I think we're ready to submit -- I'll rebase on upstream and send a pull request.  Sounds good?

**Comment by WebDrake** [comment]
> We need to add in an enforcement on sigma in the Normal constructor

For whatever reason, GitHub didn't show that in the diff I was looking at -- but I see you already did. :-P

So I think we're good to submit.  Give me your OK and I'll rebase and send pull request.

**Comment by WebDrake** [comment]
... noticed a small correction that needed to be made to the docs after your change to Ziggurat:
https://github.com/WebDrake/phobos/commit/384da563a3533db64f9868ec4d1474b56f74fc81

Anyway, that done, I think we're good.

**Comment by jkrempus** [comment]
>  Anyway, that done, I think we're good.

I agree.

**Comment by WebDrake** [comment]
On 12/23/2012 08:11 PM, jerro wrote:

> I agree.

Done: https://github.com/D-Programming-Language/phobos/pull/1029

**Pull request merged**
