### PR TITLE
Normal

### PR DESCRIPTION
**Pull request by jkrempus**
This corrects a few things mentioned in your pull request's comments. I hope making a pull request to this branch is the correct way to add commits to your pull request.

### CODE REVIEW

**Comment by WebDrake** [comment]
It's not going to work because I rebased on top of upstream before sending the pull request.  For these tweaks I'll make them manually myself -- for future reference I guess the best way is to newly branch from my normal-distribution branch and submit patches based against that.

**Comment by WebDrake** [comment]
Oh, before I forget -- how would you like to be credited in the std.normal author list? :-)

**Comment by jkrempus** [comment]
> Oh, before I forget -- how would you like to be credited in the std.normal author list? :-)

With my full name, as "Jernej Krempuš".

**Comment by WebDrake** [comment]
Any website to link to? :-)

**Comment by jkrempus** [comment]
No, don't have one.

**Pull request closed without merging**
